// Curated Font Awesome registry. We register only the icons the app
// actually uses (all solid) instead of the full packs — this keeps the
// bundle small. When you reference a new `fa-solid fa-*` in a template,
// add its import here too, or it will render blank.
import {
  faArrowRight,
  faArrowRightArrowLeft,
  faArrowRightFromBracket,
  faBagShopping,
  faBasketShopping,
  faBoxOpen,
  faCheck,
  faChevronDown,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleNotch,
  faCircleUser,
  faCreditCard,
  faDollarSign,
  faEllipsis,
  faFileArrowUp,
  faFlagCheckered,
  faGlobe,
  faHouse,
  faHryvniaSign,
  faInbox,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMoon,
  faPen,
  faPhone,
  faPlus,
  faReceipt,
  faSun,
  faTableCellsLarge,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faUsers,
  faWarehouse,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

export const appIcons = [
  faArrowRight,
  faArrowRightArrowLeft,
  faArrowRightFromBracket,
  faBagShopping,
  faBasketShopping,
  faBoxOpen,
  faCheck,
  faChevronDown,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleNotch,
  faCircleUser,
  faCreditCard,
  faDollarSign,
  faEllipsis,
  faFileArrowUp,
  faFlagCheckered,
  faGlobe,
  faHouse,
  faHryvniaSign,
  faInbox,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMoon,
  faPen,
  faPhone,
  faPlus,
  faReceipt,
  faSun,
  faTableCellsLarge,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faUsers,
  faWarehouse,
  faXmark,
]
